import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/transaction_model.dart';

class ReportService {
  /// Generate and print/share PDF report
  Future<void> generateTransactionReport(
    List<MoneyTransaction> transactions,
    String dateRange,
    String typeFilter,
  ) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateFormatter = DateFormat('MMM d, yyyy h:mm a');
    final currencyFormatter = NumberFormat.currency(symbol: 'ETB ', decimalDigits: 2);

    // Calculate totals
    double totalDistributed = 0;
    double totalReturned = 0;
    double totalPurchased = 0;
    
    for (var t in transactions) {
      if (t.type == 'distribution') totalDistributed += t.amount;
      else if (t.type == 'return') totalReturned += t.amount;
      else if (t.type == 'purchase') totalPurchased += t.amount;
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            // Header
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Stitch Worker Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(dateFormatter.format(now), style: const pw.TextStyle(fontSize: 12)),
                ],
              ),
            ),
            
            pw.SizedBox(height: 20),
            
            // Filter Info
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Report Criteria', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 5),
                  pw.Text('Date Range: $dateRange'),
                  pw.Text('Type Filter: $typeFilter'),
                  pw.Text('Total Records: ${transactions.length}'),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // Summary Table
            pw.Text('Summary', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 10),
            pw.Table.fromTextArray(
              headers: ['Distributed', 'Returned', 'Coffee Purchase', 'Net Flow'],
              data: [
                [
                  currencyFormatter.format(totalDistributed),
                  currencyFormatter.format(totalReturned),
                  currencyFormatter.format(totalPurchased),
                  currencyFormatter.format(totalDistributed - totalReturned - totalPurchased),
                ]
              ],
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey800),
              cellAlignment: pw.Alignment.centerRight,
            ),

            pw.SizedBox(height: 20),

            // Transactions Table
            pw.Text('Transactions', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 10),
            pw.Table.fromTextArray(
              context: context,
              headers: ['Date', 'Worker', 'Type', 'Amount'],
              data: transactions.map((t) => [
                DateFormat('MMM d, HH:mm').format(t.createdAt),
                t.workerName,
                t.typeDisplay,
                currencyFormatter.format(t.amount),
              ]).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey600),
              rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300))),
              cellAlignment: pw.Alignment.centerLeft,
              cellAlignments: {
                3: pw.Alignment.centerRight,
              },
            ),
            
            pw.SizedBox(height: 20),
            pw.Footer(
              leading: pw.Text('Generated by Stitch Worker App'),
              trailing: pw.Text('Page ${context.pageNumber} of ${context.pagesCount}'),
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Stitch_Report_${DateFormat('yyyyMMdd_HHmm').format(now)}',
    );
  }
}
